name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
      - cron: "0 13 * * 1"  # Every Monday at 9AM EST

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Test pre-commit hooks
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit run -a

  validate-types-and-docstrings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[dev]"

      - name: isort
        run: find . -name "*.py" | xargs isort --profile black --check-only

      - name: mypy type validation
        run: mypy src

      - name: darglint docstring validation
        run: darglint src --strictness=short --ignore-raise=ValueError

  tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[tests]"

      - name: Run Python tests
        run: pytest --cov=refractiveindex2 tests

  tests-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[tests]"

      - name: Run Python tests
        run: pytest --cov=refractiveindex2 tests
